# This package provides the API client code for interacting with the Immich server.
#
# Architectural notes:
# - There are two architectural levels:
#   1. Direct access to the Immich API (thin client, low-level bindings).
#   2. Higher-level helpers that build on the client, adding features such as event logging and automation.
#
# Future extension:
# - A possible third level may be introduced to encapsulate retry and timeout logic.
#   Currently, retry/timeouts are distributed across various classes, but a dedicated layer would
#   centralize and standardize this behavior for all API interactions.
#
# Convention:
# - The structure and naming of this package intentionally mirror the official Immich client library
#   (as generated by the Immich OpenAPI tool), to make usage and migration predictable and familiar.
